### ISSUE TITLE
Error message "Failed to activate the project-view package"

### ISSUE THREAD

**Issue by ThomasLandauer** [subesokun/atom-project-view#28]
[Enter steps to reproduce:]

1. Tried to install the package from within Atom.
2. Error message shows up.

However, the package seems to work.

Any text below this line was created automatically by Atom when I clicked the "Create issue on the project-view package" button.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [project-view](https://github.com/subesokun/atom-project-view) package 0.6.4

### Stack Trace

Failed to activate the project-view package

```
At Cannot read property 'observe' of undefined

TypeError: Cannot read property 'observe' of undefined
    at Object.subscribeUpdateEvents (/packages/project-view/lib/project-view.coffee:103:15)
    at Object.initProjectView (/packages/project-view/lib/project-view.coffee:66:10)
    at Object.activate (/packages/project-view/lib/project-view.coffee:36:6)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -7:20.4.0 tree-view:move (span.name.icon.icon-repo)
     -2:38.5.0 settings-view:open (div.tool-panel.tree-view)
     -1:08.1.0 tree-view:toggle-focus (div.package-detail.panels-item)
     -1:07.5.0 tree-view:open-selected-entry-in-pane-1 (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autoclose-html 0.23.0 
busy-signal 1.4.3 
ctrl-dir-scroll 0.2.5 
docblockr 0.13.7 
file-icons 2.1.24 
highlight-line 0.12.0 
highlight-selected 0.14.0 
ide-php 0.7.15 
intentions 1.1.5 
language-markdown 0.26.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
minimap 4.29.8 
php-twig 4.0.0 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
project-view 0.6.4 
sass-autocompile 0.13.5 
todo-show 2.3.2 
```

**Comment by subesokun** [comment]
@ThomasLandauer I've published now v0.6.5, please let me know if that solved your issue.

**Comment by ThomasLandauer** [comment]
I'm not sure.

I uninstalled the package, then restarted Atom, then installed it again. No error message anymore. But the installed version still shows 0.6.4, and gives me a button to upgrade to 0.6.5.

Should I try again tomorrow?

Minor other bug:
After the upgrade, the new version number is missing in the success message:

> Restart Atom to complete the update of project-view.
> 0.6.4 -> undefined
